/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Winx */

#ifndef _Included_Winx
#define _Included_Winx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Winx
 * Method:    startupV8
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Winx_startupV8
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
